export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_CURRENT_USERNAME = 'UPDATE_CURRENT_USERNAME';
export const UPDATE_USERS_ONLINE = 'UPDATE_USERS_ONLINE';

export const UPDATE_ALL_GAMES = 'UPDATE_ALL_GAMES';
export const UPDATE_OPEN_GAME = 'UPDATE_OPEN_GAME';
export const UPDATE_OPEN_GAME_NUMBER = 'UPDATE_OPEN_GAME_NUMBER';
