export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_CURRENT_USERNAME = 'UPDATE_CURRENT_USERNAME';
export const UPDATE_USERS_ONLINE = 'UPDATE_USERS_ONLINE';

export const UPDATE_ALL_GAMES_INFO = 'UPDATE_ALL_GAMES_INFO';
export const UPDATE_OPEN_GAME_INFO = 'UPDATE_OPEN_GAME_INFO';
export const UPDATE_OPEN_GAME_NUMBER = 'UPDATE_OPEN_GAME_NUMBER';
